In [1]:
from lago.lago import LinkStream, lago_communities
import pandas as pd

filename = 'syn_data/syn_net_p0.8_mu0.2.csv'
df = pd.read_csv(filename, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)
time_links = df.values.tolist()

## Initiate empty temporal network (as a link stream)
my_linkstream = LinkStream(is_stream_graph=False)
my_linkstream.add_links(time_links)

# NOTE time links can also be imported from txt files with the read_txt() method

## Display linkstream informations
print(f"The link stream consists of {my_linkstream.nb_edges} temporal edges (or time links) accross {my_linkstream.nb_nodes} nodes and {my_linkstream.network_duration} time steps, of which only {my_linkstream.nb_timesteps} contain activity.")

The link stream consists of 482 temporal edges (or time links) accross 50 nodes and 2896 time steps, of which only 482 contain activity.

/var/folders/g1/wg9xf7ks75b49ljdm6l5zy280000gp/T/ipykernel_19822/290250574.py:6: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(filename, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

In [2]:
df.head(5)

   source  destination  timestamp
0       9           12          2
1       8            9          9
2      10           19         18
3       2            9         24
4       2           17         31

In [16]:
import importlib
from lago.lago import LinkStream, lago_communities

my_linkstream = LinkStream(is_stream_graph=False)
my_linkstream.add_links(time_links)

## Compute dynamic communities
dynamic_communities = lago_communities(
    my_linkstream,
    nb_iter=1, # run LAGO 3 times and return best result
    )

# Each dynamic community is represented by a list of (<node>, <time instant>)

print(f"{len(dynamic_communities)} dynamic communities have been found")

import importlib
import lago.l_modularity_function as lmf

importlib.reload(lmf)
longitudinal_modularity = lmf.longitudinal_modularity

## Compute Longitudinal Modularity score
## (the higher the better / maximum is 1)
long_mod_score = longitudinal_modularity(
    my_linkstream, 
    dynamic_communities,
    lex_type="MM",
    omega=2
    )

print(f"Longitudinal Modularity score of {long_mod_score} ")

9 dynamic communities have been found
community nb interaction:{7: 92, 3: 90, 0: 58, 1: 132, 4: 84, 5: 98, 8: 80, 2: 170, 6: 110}
defaultdict(<class 'float'>, {20: 189, 39: 171, 2: 1, 5: 388, 43: 289, 9: 382, 46: 194, 34: 385, 44: 243, 18: 422, 24: 22, 1: 151, 3: 192, 30: 27, 15: 270, 41: 1, 37: 1})
defaultdict(<class 'float'>, {26: 761, 36: 1897, 42: 1083, 49: 1242, 14: 66, 33: 2092, 15: 1143, 7: 320, 3: 267, 16: 1790, 40: 1, 0: 251, 21: 1005, 25: 1229, 12: 1258, 28: 10, 38: 1146, 31: 9, 39: 36, 24: 30, 2: 71, 43: 62, 37: 17})
defaultdict(<class 'float'>, {19: 1421, 31: 1550, 28: 941, 37: 868, 7: 91, 41: 47, 9: 878, 32: 1423, 35: 1392, 21: 96, 25: 343, 47: 1584, 27: 987, 48: 295, 4: 1478, 29: 1520, 22: 366, 11: 761, 45: 246, 24: 497, 8: 1, 34: 1, 39: 181, 12: 268, 18: 1, 40: 1})
defaultdict(<class 'float'>, {29: 1196, 35: 817, 22: 889, 37: 415, 21: 644, 31: 684, 44: 95, 32: 773, 0: 133, 13: 420, 19: 521, 24: 116, 2: 374, 47: 126, 4: 182, 40: 36, 43: 1, 28: 842, 3: 472, 14: 1, 11: 30, 1: 1, 9: 1})
defaultdict(<class 'float'>, {10: 952, 1: 1334, 45: 2001, 11: 12, 30: 739, 34: 577, 2: 1174, 43: 12, 23: 76, 17: 1, 14: 25, 20: 434, 5: 631, 27: 512, 32: 186, 41: 495, 39: 2, 6: 1, 40: 6, 26: 28, 24: 25, 38: 1, 48: 1, 3: 1})
defaultdict(<class 'float'>, {39: 126, 40: 947, 11: 316, 4: 131, 20: 583, 26: 399, 43: 444, 6: 267, 41: 55, 10: 508, 44: 207, 17: 344, 34: 410, 5: 395, 13: 433, 47: 193, 18: 327, 8: 403, 48: 89, 46: 66, 9: 1, 7: 45, 30: 266, 0: 1})
defaultdict(<class 'float'>, {39: 112, 6: 402, 15: 144, 17: 330, 8: 269, 44: 489, 16: 321, 24: 352, 23: 728, 18: 471, 22: 1, 43: 651, 49: 461, 13: 800, 41: 646, 34: 1, 48: 172, 5: 155, 3: 511, 46: 420, 20: 1, 14: 645, 7: 129, 33: 1, 37: 1, 30: 61})
defaultdict(<class 'float'>, {42: 600, 10: 494, 44: 97, 38: 407, 47: 383, 12: 454, 26: 287, 6: 499, 14: 390, 25: 420, 2: 1, 7: 422, 17: 266, 0: 115, 23: 509, 19: 291, 9: 67, 48: 436, 49: 1, 24: 2, 45: 1, 11: 1, 39: 51, 43: 40})
defaultdict(<class 'float'>, {44: 1153, 34: 324, 18: 431, 0: 1193, 24: 16, 11: 143, 17: 683, 14: 614, 23: 177, 6: 1, 46: 537, 8: 748, 3: 64, 48: 493, 7: 336, 5: 1, 39: 531, 13: 615, 2: 1, 20: 42, 28: 1})
community expectations mme from @l_modularity_function.py:{0: 0.007829118018169047, 1: 0.02585436365302565, 2: 0.051935398072166614, 3: 0.02224930854198134, 4: 0.013535801560709127, 5: 0.020815455611867942, 6: 0.025740905199854527, 7: 0.016655506226637896, 8: 0.020081321200529204}
Longitudinal Modularity score of 0.38244

In [17]:
from __future__ import annotations

from typing import Dict, Hashable, Iterable, Tuple, Any, Optional, Union
import pandas as pd

Node = Hashable
Time = Hashable


def commu_dict_to_interaction_csv(
    commu_dict: Dict[Any, Iterable[Tuple[Node, Time]]],
    syn_csv_path: str = "syn_net.csv",
    out_csv_path: str = "labeled_syn_net.csv",
    *,
    source_col: Union[str, int] = "source",
    destination_col: Union[str, int] = "destination",
    timestamp_col: Union[str, int] = "timestamp",
    syn_header: Optional[int] = "infer",
    syn_sep: str = ",",
    syn_skip_first_row: bool = False,

    node_dtype: Any = int,
    time_dtype: Any = int,

    unknown_commu_value: Any = -1,

    on_conflict: str = "error",
) -> pd.DataFrame:

    syn_df = pd.read_csv(
        syn_csv_path,
        sep=syn_sep,
        header=syn_header,
        skiprows=1 if syn_skip_first_row else None,
        usecols=[source_col, destination_col, timestamp_col],
    ).copy()

    syn_df[source_col] = syn_df[source_col].astype(node_dtype)
    syn_df[destination_col] = syn_df[destination_col].astype(node_dtype)
    syn_df[timestamp_col] = syn_df[timestamp_col].astype(time_dtype)

    active_pairs = set(zip(syn_df[source_col].tolist(), syn_df[timestamp_col].tolist()))
    active_pairs |= set(zip(syn_df[destination_col].tolist(), syn_df[timestamp_col].tolist()))

    node_time_to_commu: Dict[Tuple[Node, Time], Any] = {}

    def _assign(k: Tuple[Node, Time], commu: Any):
        if k not in node_time_to_commu:
            node_time_to_commu[k] = commu
            return
        if node_time_to_commu[k] == commu:
            return
        if on_conflict == "keep_first":
            return
        if on_conflict == "keep_last":
            node_time_to_commu[k] = commu
            return
        raise ValueError(f"Conflict: (node,time)={k} appears in multiple communities: "
                         f"{node_time_to_commu[k]} vs {commu}")

    for commu, pairs in commu_dict.items():
        for u, t in pairs:
            u = node_dtype(u)
            t = time_dtype(t)
            k = (u, t)
            if k in active_pairs:
                _assign(k, commu)

    def _lookup(u: int, t: int):
        return node_time_to_commu.get((u, t), unknown_commu_value)

    syn_df["source_commu"] = [
        _lookup(int(s), int(t)) for s, t in zip(syn_df[source_col], syn_df[timestamp_col])
    ]
    syn_df["destination_commu"] = [
        _lookup(int(d), int(t)) for d, t in zip(syn_df[destination_col], syn_df[timestamp_col])
    ]

    out_df = syn_df.rename(
        columns={
            source_col: "source",
            destination_col: "destination",
            timestamp_col: "timestamp",
        }
    )[["source", "destination", "timestamp", "source_commu", "destination_commu"]]

    out_df.to_csv(out_csv_path, index=False)
    return out_df

real_communities = commu_dict_to_interaction_csv(
    dynamic_communities,
    syn_csv_path="syn_data/syn_net_p0.8_mu0.2.csv",
    out_csv_path="result/syn_net_p0.8_mu0.2.csv",
    syn_header="infer", 
    syn_skip_first_row=False,
    unknown_commu_value=-1, 
    on_conflict="error",
)

(real_communities.head(10))

   source  destination  timestamp  source_commu  destination_commu
0      14           25          7             7                  7
1       6           17         13             7                  7
2      13           31         20             3                  3
3       5           34         27             0                  0
4       9           25         33             7                  7
5       9           10         39             7                  7
6      11           29         45             3                  3
7       7           43         54             7                  7
8      34           39         62             0                  0
9      19           43         65             7                  7

In [ ]:
from __future__ import annotations

from pathlib import Path
import pandas as pd
import Baseline

def batch_lago_label_syn_folder(
    syn_dir: str | Path = "syn_data",
    out_dir: str | Path = "results/lago",
    *,
    nb_iter: int = 50,
    is_stream_graph: bool = False,
    info_logging: bool = False,
    glob_pattern: str = "*.csv",

    syn_header: str | int | None = "infer",
    syn_skip_first_row: bool = False,
    unknown_commu_value=-1,
    on_conflict: str = "error",
) -> str:
    syn_dir = Path(syn_dir)
    if not syn_dir.exists() or not syn_dir.is_dir():
        raise FileNotFoundError(f"Input directory not found: {syn_dir}")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    files = sorted(syn_dir.glob(glob_pattern))
    if not files:
        raise FileNotFoundError(f"No files matching '{glob_pattern}' found in: {syn_dir}")

    summary_rows = []

    for fp in files:
        if not fp.is_file():
            continue

        out_csv_path = out_dir / fp.name

        try:
            dynamic_communities, long_mod_score, runtime_sec = Baseline.lago_community(
                str(fp),
                nb_iter=nb_iter,
                is_stream_graph=is_stream_graph,
                info_logging=info_logging,
            )


            commu_dict_to_interaction_csv(
                dynamic_communities,
                syn_csv_path=str(fp),
                out_csv_path=str(out_csv_path),
                syn_header=syn_header,
                syn_skip_first_row=syn_skip_first_row,
                unknown_commu_value=unknown_commu_value,
                on_conflict=on_conflict,
            )

            summary_rows.append({
                "filename": fp.name,
                "out_csv": str(out_csv_path),
                "long_modularity": float(long_mod_score),
                "runtime_sec": float(runtime_sec),
                "n_dynamic_communities": int(len(dynamic_communities)) if hasattr(dynamic_communities, "__len__") else None,
                "status": "ok",
            })

        except Exception as e:
            summary_rows.append({
                "filename": fp.name,
                "out_csv": str(out_csv_path),
                "long_modularity": None,
                "runtime_sec": None,
                "n_dynamic_communities": None,
                "status": f"error: {type(e).__name__}: {e}",
            })

    summary_csv = out_dir / "summary.csv"
    pd.DataFrame(summary_rows).to_csv(summary_csv, index=False)

    return str(summary_csv)

In [ ]:
from Baseline import lago_community


summary = batch_lago_label_syn_folder(
    syn_dir="syn_data",
    out_dir="results/lago",
    nb_iter=5,
    syn_header="infer",
    syn_skip_first_row=False,
    unknown_commu_value=-1,
    on_conflict="error",
)

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{6: 52, 5: 26, 1: 180, 4: 122, 0: 132, 2: 80, 7: 190, 3: 94}
defaultdict(<class 'float'>, {32: 1683, 47: 253, 16: 2054, 46: 1326, 11: 912, 36: 201, 31: 36, 49: 2383, 27: 715, 15: 182, 13: 1551, 45: 1702, 9: 1437, 17: 207, 23: 2047, 26: 167, 0: 73, 25: 1})
defaultdict(<class 'float'>, {18: 2440, 31: 464, 29: 1881, 12: 1413, 41: 1933, 1: 1385, 11: 502, 19: 2499, 30: 1915, 8: 1104, 43: 2445, 6: 634, 15: 1, 39: 892, 33: 793, 35: 1, 34: 1})
defaultdict(<class 'float'>, {35: 1475, 3: 1871, 24: 2032, 31: 266, 38: 982, 44: 1799, 12: 132, 37: 657, 34: 394, 15: 165, 27: 1002, 25: 1, 29: 68})
defaultdict(<class 'float'>, {42: 442, 8: 239, 6: 729, 36: 150, 28: 135, 7: 509, 22: 604, 33: 517, 10: 560, 15: 374, 46: 1, 0: 299, 38: 212, 30: 160, 14: 435, 25: 242, 4: 711, 45: 1, 2: 185, 26: 79, 48: 1})
defaultdict(<class 'float'>, {4: 473, 48: 850, 25: 790, 0: 625, 20: 784, 26: 76, 34: 344, 22: 529, 10: 592, 28: 114, 6: 908, 2: 234, 42: 266, 21: 185, 40: 739, 17: 113, 14: 353, 37: 377, 15: 322, 36: 272, 7: 744})
defaultdict(<class 'float'>, {5: 804, 4: 325, 11: 199, 23: 330, 9: 420, 38: 328, 47: 52, 1: 1})
defaultdict(<class 'float'>, {1: 497, 24: 576, 32: 443, 35: 449, 27: 1, 2: 468, 3: 45, 31: 311, 39: 343, 44: 326, 42: 273, 41: 403, 21: 1})
defaultdict(<class 'float'>, {48: 466, 40: 1429, 42: 714, 25: 909, 0: 862, 33: 846, 14: 1091, 7: 958, 10: 742, 26: 640, 47: 1392, 2: 766, 21: 1512, 20: 1576, 4: 743, 46: 510, 5: 1541, 34: 96, 17: 1499, 39: 44, 37: 510, 28: 607, 36: 1136, 15: 103, 38: 366})
community expectations mme from @l_modularity_function.py:{0: 0.02594851364444412, 1: 0.04609247947832961, 2: 0.01334248613426484, 3: 0.02202485905049656, 4: 0.03626346186528264, 5: 0.0020165652560609412, 6: 0.00663323454739269, 7: 0.08181436237532184}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 88, 6: 84, 2: 122, 1: 102, 3: 196, 7: 134, 5: 76, 4: 90}
defaultdict(<class 'float'>, {44: 356, 13: 299, 27: 369, 33: 438, 2: 180, 25: 350, 15: 453, 32: 236, 22: 469, 30: 466, 0: 502, 8: 486, 41: 340, 42: 371, 38: 39, 21: 382, 31: 1, 43: 316})
defaultdict(<class 'float'>, {16: 2726, 23: 957, 28: 1198, 42: 11, 32: 380, 26: 1, 20: 1362, 49: 421, 19: 158, 6: 87, 34: 2333, 2: 12, 31: 164, 45: 90, 13: 276, 17: 1, 30: 1, 15: 508, 46: 1, 36: 1, 40: 1})
defaultdict(<class 'float'>, {1: 1908, 11: 2520, 40: 515, 3: 980, 21: 2041, 14: 268, 9: 224, 12: 1424, 36: 77, 7: 1730, 42: 1, 5: 2108, 47: 2256, 28: 354, 26: 78, 27: 44, 13: 1, 15: 593, 32: 1, 19: 1, 37: 1, 18: 52})
defaultdict(<class 'float'>, {24: 614, 22: 1033, 32: 428, 25: 1453, 42: 181, 4: 1497, 17: 1099, 33: 1453, 36: 372, 15: 436, 19: 405, 41: 1138, 3: 456, 2: 1193, 0: 1211, 38: 1450, 18: 1513, 8: 1394, 44: 1, 49: 533, 23: 524, 10: 1, 37: 1393, 43: 135, 6: 47})
defaultdict(<class 'float'>, {36: 1, 38: 376, 1: 39, 37: 63, 12: 426, 26: 122, 20: 638, 4: 283, 44: 383, 2: 537, 0: 49, 33: 236, 42: 643, 39: 1, 13: 94, 43: 84, 24: 222, 8: 52, 22: 433, 32: 275, 17: 14, 14: 473, 41: 94, 5: 328, 48: 1})
defaultdict(<class 'float'>, {37: 1, 9: 455, 35: 792, 48: 170, 19: 194, 26: 281, 10: 685, 13: 327, 27: 724, 6: 551, 29: 1077, 45: 602, 49: 273, 30: 6, 28: 166, 39: 492})
defaultdict(<class 'float'>, {10: 968, 36: 455, 37: 360, 29: 654, 14: 453, 39: 508, 9: 101, 49: 545, 45: 675, 6: 484, 35: 347, 31: 330, 48: 210, 26: 526, 1: 168})
defaultdict(<class 'float'>, {24: 818, 26: 511, 40: 326, 13: 126, 36: 920, 44: 1414, 9: 1036, 31: 931, 10: 355, 14: 1012, 39: 1028, 30: 1357, 43: 225, 46: 1137, 35: 526, 27: 555, 48: 984, 29: 47, 6: 512, 7: 198, 0: 182, 2: 1, 45: 666, 42: 48})
community expectations mme from @l_modularity_function.py:{0: 0.0162789337318626, 1: 0.016151871034482058, 2: 0.024860690553978607, 3: 0.06655216523826367, 4: 0.0171542901090452, 5: 0.01563337714788553, 6: 0.017709294523861118, 7: 0.048078501357613296}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{3: 226, 1: 154, 0: 298, 4: 80, 2: 152}
defaultdict(<class 'float'>, {48: 1355, 3: 2214, 17: 807, 36: 2789, 30: 2661, 43: 2728, 35: 2781, 45: 1899, 13: 2024, 9: 2610, 16: 2503, 42: 1693, 2: 2, 41: 2402, 12: 809, 11: 2681, 15: 2198, 44: 907, 31: 1041, 40: 2275, 28: 956, 29: 92, 47: 1, 25: 682, 10: 44})
defaultdict(<class 'float'>, {12: 1246, 46: 2468, 10: 1689, 18: 1899, 28: 504, 37: 2695, 5: 1675, 32: 2592, 26: 1, 1: 2581, 30: 1, 22: 304, 34: 413, 14: 1, 47: 127})
defaultdict(<class 'float'>, {14: 1280, 0: 681, 4: 1203, 19: 466, 6: 1147, 8: 1195, 21: 1211, 17: 429, 20: 1225, 39: 1040, 33: 990, 24: 1141, 38: 1147, 10: 16, 27: 633, 23: 1223, 29: 270, 2: 512, 25: 161})
defaultdict(<class 'float'>, {19: 1687, 21: 936, 27: 2120, 24: 858, 25: 60, 49: 2516, 0: 1109, 45: 1, 6: 1494, 47: 1258, 14: 642, 18: 251, 8: 1161, 29: 1431, 20: 1410, 31: 1271, 23: 1255, 38: 1293, 33: 1177, 39: 995, 17: 522, 40: 418, 5: 137, 2: 83, 28: 1, 13: 1})
defaultdict(<class 'float'>, {26: 2212, 7: 2085, 22: 1833, 48: 751, 25: 335, 44: 443, 34: 1769, 17: 230, 4: 1098, 2: 100, 45: 1, 12: 1})
community expectations mme from @l_modularity_function.py:{0: 0.1075721859870704, 1: 0.02866196770463677, 2: 0.04765302814637742, 3: 0.08126590653036428, 4: 0.00956646116985259}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{9: 138, 4: 98, 1: 96, 5: 94, 0: 64, 2: 50, 3: 46, 6: 108, 8: 72, 10: 84, 7: 96}
defaultdict(<class 'float'>, {46: 923, 15: 1, 45: 174, 13: 2145, 35: 759, 40: 462, 38: 108, 29: 2230, 9: 2266, 4: 113, 47: 152, 25: 4, 36: 1, 43: 1, 26: 280})
defaultdict(<class 'float'>, {21: 536, 18: 1929, 17: 240, 48: 1249, 1: 2442, 34: 1437, 4: 209, 22: 52, 19: 437, 24: 2140, 43: 1646, 15: 1, 49: 1, 20: 138, 46: 411, 23: 156, 10: 26})
defaultdict(<class 'float'>, {41: 2, 46: 310, 15: 549, 14: 50, 25: 1441, 4: 1300, 21: 174, 44: 750, 45: 704, 48: 284, 8: 264, 22: 1, 39: 158})
defaultdict(<class 'float'>, {31: 1, 20: 367, 37: 604, 11: 699, 22: 494, 40: 41, 8: 1, 12: 264, 33: 347, 18: 61, 42: 652, 38: 158, 39: 292, 34: 1, 6: 208})
defaultdict(<class 'float'>, {37: 1, 20: 178, 11: 573, 27: 1, 33: 502, 8: 487, 44: 353, 6: 778, 12: 510, 21: 402, 41: 309, 38: 375, 34: 539, 22: 525, 10: 13, 36: 383, 49: 696, 26: 310, 32: 1, 19: 35, 16: 1, 14: 1})
defaultdict(<class 'float'>, {2: 983, 26: 529, 30: 346, 8: 384, 10: 109, 31: 605, 35: 839, 7: 555, 20: 98, 16: 612, 40: 433, 39: 358, 48: 121, 22: 224, 36: 328, 33: 1, 11: 15, 45: 1, 27: 360, 49: 44, 47: 162, 19: 1, 37: 1})
defaultdict(<class 'float'>, {21: 322, 49: 440, 47: 546, 41: 453, 38: 449, 2: 532, 32: 645, 39: 483, 33: 291, 8: 83, 26: 554, 10: 737, 12: 200, 16: 830, 20: 1, 14: 422, 17: 395, 44: 126, 11: 131, 6: 1, 27: 241})
defaultdict(<class 'float'>, {19: 278, 11: 539, 32: 382, 39: 454, 37: 611, 40: 395, 21: 414, 41: 255, 22: 43, 10: 413, 47: 24, 6: 1, 49: 590, 44: 190, 8: 347, 12: 91, 34: 1, 17: 179, 20: 340, 35: 148, 16: 171, 48: 1, 0: 1})
defaultdict(<class 'float'>, {47: 589, 6: 235, 19: 239, 15: 793, 16: 1, 45: 504, 28: 348, 12: 59, 43: 42, 2: 537, 10: 342, 37: 1, 41: 412, 27: 937, 22: 144, 0: 1, 36: 60, 14: 256, 4: 163, 44: 282, 32: 121})
defaultdict(<class 'float'>, {28: 1735, 0: 1020, 36: 1191, 47: 1, 7: 1278, 30: 1453, 3: 1839, 5: 1617, 40: 1091, 42: 708, 23: 1602, 19: 506, 37: 363, 22: 1, 31: 1099, 20: 1, 26: 60})
defaultdict(<class 'float'>, {33: 336, 1: 121, 16: 1, 9: 434, 41: 154, 43: 378, 23: 559, 5: 868, 38: 336, 30: 471, 13: 385, 28: 339, 7: 648, 42: 350, 31: 291, 18: 1, 3: 517, 24: 419, 12: 128, 37: 244, 45: 71, 29: 1})
community expectations mme from @l_modularity_function.py:{0: 0.00834231998138723, 1: 0.016100149757321738, 2: 0.006592509824179299, 3: 0.007842075853980087, 4: 0.021140641480066502, 5: 0.022577675823549154, 6: 0.023971760704834585, 7: 0.019311505852109456, 8: 0.012283370781101073, 9: 0.03095802864244711, 10: 0.017557416615872398}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{6: 216, 0: 130, 5: 52, 1: 118, 2: 112, 7: 116, 4: 82, 3: 98}
defaultdict(<class 'float'>, {1: 489, 15: 679, 4: 431, 31: 368, 38: 1229, 8: 1164, 3: 564, 18: 294, 21: 376, 20: 1217, 35: 106, 36: 813, 10: 655, 44: 25, 37: 1267, 32: 221, 2: 1148, 19: 913, 39: 277, 12: 639, 42: 139, 23: 316, 34: 1, 48: 1})
defaultdict(<class 'float'>, {41: 2406, 28: 970, 26: 1801, 46: 1575, 43: 2822, 17: 332, 13: 2719, 32: 70, 42: 7, 6: 1568, 2: 1, 31: 238, 45: 569, 7: 338, 47: 76, 15: 1, 35: 1, 23: 1, 1: 1})
defaultdict(<class 'float'>, {44: 2744, 8: 275, 5: 2938, 38: 1, 0: 2924, 39: 362, 48: 1126, 40: 410, 7: 302, 24: 2316, 22: 1215, 45: 39, 27: 507, 46: 1, 31: 228, 16: 337, 42: 2, 34: 1})
defaultdict(<class 'float'>, {42: 1006, 47: 910, 17: 1024, 29: 1040, 6: 1, 14: 501, 18: 383, 32: 279, 36: 877, 11: 869, 31: 1, 46: 198, 4: 854, 3: 875, 24: 1, 40: 100, 38: 1, 25: 1, 10: 1})
defaultdict(<class 'float'>, {19: 234, 23: 405, 39: 527, 20: 1069, 2: 415, 37: 1310, 35: 711, 10: 967, 12: 864, 15: 1261, 38: 515, 28: 388, 1: 2, 45: 1, 22: 79, 8: 497, 42: 1, 21: 216, 31: 1})
defaultdict(<class 'float'>, {18: 269, 31: 387, 47: 735, 11: 1174, 3: 287, 23: 1, 4: 518, 32: 825, 42: 531, 29: 1172, 21: 1146})
defaultdict(<class 'float'>, {1: 683, 9: 2999, 30: 2754, 49: 1951, 14: 2358, 3: 40, 16: 1805, 25: 2513, 40: 1139, 34: 1338, 7: 1354, 26: 558, 33: 2774, 39: 688, 17: 482, 27: 1687, 23: 246, 48: 3, 28: 2, 2: 1, 11: 1})
defaultdict(<class 'float'>, {6: 596, 48: 751, 45: 443, 35: 917, 4: 396, 8: 200, 29: 1, 22: 276, 23: 208, 19: 1081, 31: 26, 2: 85, 28: 461, 15: 413, 47: 437, 41: 79, 11: 57, 18: 887, 38: 234, 3: 89, 34: 141, 12: 659, 1: 677, 32: 313, 26: 1, 36: 1, 20: 41})
community expectations mme from @l_modularity_function.py:{0: 0.033424913745793226, 1: 0.02197892097329184, 2: 0.018564935213742164, 3: 0.01638105385383964, 4: 0.016617202760899886, 5: 0.009342803002398387, 6: 0.0579787957158902, 7: 0.027247921881724865}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 152, 1: 126, 3: 304, 4: 100, 2: 142, 5: 62}
defaultdict(<class 'float'>, {48: 435, 31: 350, 8: 567, 12: 334, 32: 419, 34: 285, 39: 449, 11: 35, 29: 74, 40: 439, 38: 529, 7: 489, 49: 509, 2: 532, 41: 520, 28: 390, 3: 414, 27: 221, 5: 155, 23: 250, 47: 1, 0: 99, 46: 418, 17: 217, 10: 375, 22: 358, 26: 1, 36: 293, 14: 113, 25: 48, 15: 245, 44: 1, 35: 120})
defaultdict(<class 'float'>, {30: 968, 37: 670, 14: 520, 4: 524, 18: 1102, 16: 978, 9: 1075, 20: 706, 40: 56, 13: 29, 39: 1, 6: 1066, 24: 400, 45: 935, 21: 402, 42: 659, 31: 1, 3: 640, 43: 970, 22: 415, 17: 143})
defaultdict(<class 'float'>, {22: 351, 20: 966, 9: 877, 48: 953, 24: 812, 4: 502, 30: 632, 14: 319, 27: 768, 46: 1707, 16: 536, 45: 1, 17: 332, 18: 744, 39: 708, 10: 897, 6: 699, 3: 1, 7: 1261, 26: 269, 43: 898, 21: 197, 42: 1, 40: 1})
defaultdict(<class 'float'>, {40: 88, 11: 1544, 38: 1739, 2: 812, 28: 1863, 37: 303, 19: 1508, 31: 811, 26: 848, 0: 1714, 12: 2018, 34: 1007, 35: 1349, 22: 469, 49: 1587, 17: 35, 1: 1727, 5: 962, 41: 1894, 15: 1439, 44: 1643, 47: 1427, 36: 667, 25: 1566, 23: 1347, 8: 1348, 29: 1272, 48: 194, 27: 191, 10: 1, 24: 1, 32: 1181, 42: 1})
defaultdict(<class 'float'>, {8: 473, 16: 458, 33: 2087, 30: 339, 5: 1, 24: 350, 40: 467, 37: 484, 27: 1, 31: 585, 45: 366, 36: 427, 7: 439, 13: 2096, 4: 539, 3: 358, 19: 362, 18: 74, 42: 68, 21: 679})
defaultdict(<class 'float'>, {36: 1, 9: 403, 29: 192, 35: 430, 17: 286, 22: 475, 27: 476, 10: 348, 0: 132, 23: 1, 34: 453, 32: 415, 11: 395, 38: 22, 47: 1, 26: 210, 2: 1, 48: 1, 14: 1, 15: 409, 20: 1})
community expectations mme from @l_modularity_function.py:{0: 0.04491435509868661, 1: 0.03404344283212232, 2: 0.04771317532117961, 3: 0.1392106170318859, 4: 0.02075249880424368, 5: 0.012635363047679017}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{2: 212, 0: 72, 6: 104, 3: 196, 1: 106, 4: 156, 5: 92, 7: 40}
defaultdict(<class 'float'>, {49: 376, 30: 1229, 3: 1311, 24: 729, 36: 1213, 48: 323, 16: 317, 38: 397, 21: 233, 47: 303, 13: 1008, 46: 1012, 14: 436, 19: 421, 35: 1, 4: 106})
defaultdict(<class 'float'>, {19: 531, 13: 572, 38: 996, 47: 752, 40: 280, 7: 525, 41: 1011, 16: 104, 30: 530, 9: 270, 28: 455, 3: 706, 35: 186, 0: 591, 4: 1134, 24: 400, 11: 507, 14: 1, 17: 66})
defaultdict(<class 'float'>, {4: 165, 42: 679, 1: 739, 37: 1090, 31: 966, 44: 837, 22: 1132, 48: 426, 12: 918, 39: 100, 43: 587, 19: 54, 45: 926, 18: 484, 28: 992, 32: 303, 35: 94, 40: 842, 25: 299, 17: 839, 38: 294, 26: 791, 14: 370, 33: 332, 8: 1000, 11: 471, 47: 498, 9: 908, 20: 393, 16: 249, 6: 1, 10: 461, 49: 1, 21: 30, 15: 99})
defaultdict(<class 'float'>, {8: 461, 33: 478, 35: 998, 5: 1165, 43: 1169, 21: 751, 45: 1208, 20: 1233, 48: 1116, 49: 1153, 10: 1206, 12: 922, 39: 1229, 40: 758, 24: 468, 9: 627, 22: 1156, 28: 209, 25: 695, 46: 754, 32: 1015, 31: 424, 14: 1, 15: 525, 1: 1, 42: 26, 44: 1})
defaultdict(<class 'float'>, {27: 1372, 29: 1644, 42: 276, 33: 351, 41: 325, 2: 1488, 36: 697, 0: 1014, 21: 144, 23: 1570, 18: 1467, 37: 1384, 44: 392, 26: 796, 34: 1527, 22: 535, 4: 590, 6: 1084, 1: 193, 30: 304, 9: 1, 17: 127, 15: 1})
defaultdict(<class 'float'>, {17: 581, 40: 499, 46: 1, 11: 615, 25: 315, 49: 384, 35: 70, 12: 408, 39: 386, 5: 303, 8: 458, 28: 361, 19: 502, 15: 145, 31: 210, 32: 277, 45: 573, 44: 152, 38: 1, 33: 1})
defaultdict(<class 'float'>, {6: 643, 25: 219, 0: 1052, 7: 297, 21: 396, 27: 1077, 33: 556, 41: 434, 23: 997, 34: 1054, 17: 74, 35: 19, 29: 946, 5: 804, 44: 150, 2: 892, 42: 231, 10: 1, 18: 351, 39: 1})
defaultdict(<class 'float'>, {47: 201, 24: 519, 36: 450, 14: 187, 13: 370, 10: 431, 3: 251, 48: 438, 45: 1, 16: 1, 33: 1})
community expectations mme from @l_modularity_function.py:{0: 0.0157195606857241, 1: 0.023066860231473165, 2: 0.07821853923309845, 3: 0.0661332114303381, 4: 0.0433091858029391, 5: 0.01630961885505968, 6: 0.022887026617190886, 7: 0.0032890061418408114}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{3: 118, 6: 182, 0: 94, 2: 28, 7: 74, 5: 108, 1: 228, 4: 124}
defaultdict(<class 'float'>, {39: 318, 46: 58, 40: 1797, 42: 903, 41: 1705, 22: 899, 11: 499, 29: 1985, 20: 780, 3: 1198, 33: 122, 2: 1, 13: 1, 16: 711})
defaultdict(<class 'float'>, {44: 1766, 4: 1325, 49: 1645, 14: 884, 8: 836, 12: 252, 21: 441, 15: 971, 9: 1658, 25: 1436, 13: 877, 27: 1435, 5: 624, 48: 1088, 45: 1378, 33: 187, 36: 1653, 10: 1289, 38: 568, 35: 946, 47: 1289, 16: 19, 31: 1, 17: 1})
defaultdict(<class 'float'>, {43: 1, 12: 211, 27: 353, 13: 679, 22: 369, 34: 72, 23: 272, 42: 1, 44: 1, 8: 1, 37: 407, 31: 267})
defaultdict(<class 'float'>, {47: 811, 14: 1453, 4: 2, 48: 1176, 10: 1139, 46: 181, 44: 528, 9: 656, 33: 539, 27: 297, 25: 433, 49: 736, 26: 1259, 36: 599, 15: 814, 21: 1120, 38: 198, 2: 6, 23: 1, 39: 2, 35: 1, 12: 1})
defaultdict(<class 'float'>, {24: 955, 46: 914, 11: 841, 2: 1242, 23: 975, 42: 781, 21: 605, 14: 410, 29: 892, 20: 970, 33: 196, 31: 1, 3: 600, 39: 1, 40: 784, 41: 570, 26: 1023, 45: 1, 12: 1, 43: 1, 6: 9, 28: 240, 37: 900, 17: 1})
defaultdict(<class 'float'>, {7: 583, 28: 1122, 30: 1529, 16: 1179, 0: 1167, 46: 1, 31: 405, 17: 399, 19: 721, 12: 416, 24: 831, 15: 122, 32: 62, 37: 314, 45: 2, 39: 698, 4: 373, 20: 366, 26: 108, 13: 266, 23: 1, 38: 89, 22: 215})
defaultdict(<class 'float'>, {34: 2429, 7: 1840, 1: 2696, 11: 998, 2: 972, 43: 1501, 6: 2912, 18: 2864, 32: 1890, 31: 477, 5: 2072, 0: 381, 19: 873, 35: 609, 17: 1, 12: 1, 23: 1})
defaultdict(<class 'float'>, {8: 1295, 38: 1299, 24: 528, 45: 598, 32: 307, 46: 457, 28: 1229, 30: 674, 23: 246, 47: 194, 36: 21, 37: 1, 35: 222, 39: 1, 43: 279, 42: 10})
community expectations mme from @l_modularity_function.py:{0: 0.014425379198175424, 1: 0.07091615728656744, 2: 0.0025031082446611975, 3: 0.02899912538066277, 4: 0.03039326094207578, 5: 0.019810258877027555, 6: 0.040991833879776805, 7: 0.011950237234649571}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{1: 68, 6: 114, 2: 84, 8: 104, 0: 96, 4: 206, 5: 118, 3: 62, 7: 28}
defaultdict(<class 'float'>, {17: 1577, 1: 1, 23: 458, 27: 1, 20: 847, 44: 1099, 8: 124, 16: 1670, 24: 1, 29: 999, 28: 1455, 35: 1684, 38: 330, 14: 611, 7: 1, 45: 55, 19: 1, 33: 1, 41: 1, 34: 1})
defaultdict(<class 'float'>, {36: 1247, 14: 1432, 13: 733, 18: 586, 34: 735, 40: 743, 1: 880, 12: 340, 6: 387, 0: 1581, 21: 127, 11: 525, 7: 1, 22: 1, 27: 1})
defaultdict(<class 'float'>, {3: 625, 32: 853, 48: 384, 26: 78, 34: 299, 13: 256, 23: 574, 46: 134, 31: 69, 30: 436, 40: 890, 39: 308, 4: 60, 42: 1084, 37: 196, 9: 884, 19: 127, 41: 1, 47: 976, 8: 2, 12: 1})
defaultdict(<class 'float'>, {32: 17, 29: 438, 5: 364, 18: 1005, 44: 202, 49: 776, 48: 1106, 11: 33, 43: 18, 35: 180, 28: 360, 20: 52, 19: 98, 4: 451, 41: 2, 24: 1, 8: 1, 22: 1, 10: 12, 31: 95, 45: 1, 1: 1})
defaultdict(<class 'float'>, {31: 605, 9: 1417, 19: 493, 32: 1392, 4: 358, 11: 171, 47: 665, 46: 1653, 13: 767, 39: 789, 7: 1329, 24: 1538, 34: 768, 3: 1796, 43: 791, 0: 353, 37: 1198, 38: 372, 26: 1439, 40: 100, 29: 448, 49: 641, 2: 1456, 12: 1300, 41: 1, 44: 1, 23: 1, 30: 743, 1: 83, 20: 173})
defaultdict(<class 'float'>, {33: 1429, 21: 890, 8: 947, 25: 1489, 22: 1309, 41: 529, 47: 12, 5: 779, 15: 966, 23: 1, 6: 275, 45: 353, 10: 866, 27: 1314, 42: 792, 38: 145, 39: 1, 14: 50, 43: 1, 1: 1})
defaultdict(<class 'float'>, {41: 392, 8: 126, 49: 567, 28: 257, 1: 461, 25: 214, 27: 420, 11: 458, 20: 842, 18: 157, 5: 414, 44: 1, 24: 9, 23: 385, 17: 404, 19: 332, 48: 55, 12: 1, 45: 1218, 29: 141, 39: 371, 4: 653, 35: 1, 7: 72, 43: 1, 37: 1, 16: 1})
defaultdict(<class 'float'>, {6: 640, 21: 198, 36: 777, 0: 287, 37: 360, 42: 1, 38: 1, 1: 134, 15: 1, 35: 1})
defaultdict(<class 'float'>, {39: 31, 25: 589, 27: 358, 33: 460, 38: 988, 22: 1092, 31: 587, 46: 117, 21: 1033, 7: 43, 10: 638, 2: 846, 15: 652, 24: 155, 30: 174, 5: 583, 43: 844, 41: 32, 12: 103, 11: 1, 13: 1})
community expectations mme from @l_modularity_function.py:{0: 0.01574673544557022, 1: 0.01254442627121866, 2: 0.015658323659050847, 3: 0.007673878441248316, 4: 0.07727125243601399, 5: 0.03187899428788222, 6: 0.022815861029666193, 7: 0.002177893644096065, 8: 0.02789409239766779}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{9: 206, 6: 98, 5: 16, 4: 84, 2: 44, 1: 94, 3: 60, 8: 84, 10: 138, 0: 38, 7: 54}
defaultdict(<class 'float'>, {10: 378, 24: 263, 38: 666, 37: 108, 26: 186, 5: 249, 6: 1, 1: 774, 35: 1, 20: 195, 2: 481, 19: 287, 30: 61, 14: 1})
defaultdict(<class 'float'>, {38: 1978, 26: 131, 28: 213, 31: 886, 12: 1663, 32: 102, 19: 93, 21: 1037, 25: 175, 2: 346, 23: 110, 47: 301, 7: 320, 15: 573, 35: 432, 42: 1354, 9: 84, 37: 17, 3: 1, 4: 10, 24: 1})
defaultdict(<class 'float'>, {24: 1, 10: 1, 27: 512, 32: 186, 45: 2151, 30: 851, 34: 182, 1: 323, 39: 1, 41: 495, 40: 6, 5: 1, 2: 17, 17: 1, 11: 12, 48: 1, 31: 1})
defaultdict(<class 'float'>, {17: 290, 5: 1, 48: 1, 18: 1, 46: 125, 2: 111, 11: 143, 13: 327, 44: 479, 34: 308, 22: 1, 7: 336, 14: 244, 8: 1, 39: 531, 23: 177, 0: 155, 20: 42, 6: 1, 19: 52, 24: 16})
defaultdict(<class 'float'>, {36: 1897, 15: 786, 25: 615, 33: 2092, 16: 2469, 21: 560, 49: 1367, 14: 66, 3: 1, 0: 485, 22: 504, 40: 1, 24: 1, 39: 35, 17: 1, 6: 1, 19: 98})
defaultdict(<class 'float'>, {39: 1, 7: 422, 43: 12, 2: 324, 11: 598, 19: 1, 18: 1, 29: 1, 30: 1})
defaultdict(<class 'float'>, {13: 420, 2: 291, 35: 781, 24: 116, 22: 889, 8: 295, 9: 1, 32: 773, 40: 36, 11: 146, 28: 957, 37: 415, 29: 850, 44: 191, 3: 539, 19: 521, 0: 212, 46: 1, 4: 764, 47: 242, 31: 1, 25: 1, 1: 1, 14: 1})
defaultdict(<class 'float'>, {5: 155, 39: 112, 3: 187, 18: 471, 44: 641, 43: 290, 15: 51, 17: 330, 24: 67, 20: 1, 23: 347, 34: 1, 16: 249, 0: 1, 33: 1, 8: 269, 13: 35, 37: 1})
defaultdict(<class 'float'>, {49: 461, 13: 433, 1: 50, 0: 79, 46: 420, 20: 44, 41: 711, 43: 950, 3: 1309, 23: 497, 48: 737, 34: 151, 7: 502, 6: 228, 14: 511, 8: 72, 25: 1, 30: 98, 18: 1, 10: 225, 17: 1, 2: 1})
defaultdict(<class 'float'>, {23: 391, 10: 1208, 30: 27, 43: 1154, 26: 909, 3: 192, 20: 977, 8: 233, 12: 377, 34: 1114, 39: 452, 9: 539, 40: 947, 44: 813, 48: 732, 25: 420, 6: 976, 7: 45, 24: 39, 17: 1274, 0: 1, 46: 539, 15: 270, 41: 433, 18: 1064, 47: 570, 5: 1007, 13: 433, 1: 151, 14: 390, 37: 1, 19: 1, 42: 1})
defaultdict(<class 'float'>, {24: 543, 32: 614, 26: 226, 9: 603, 47: 1024, 31: 1083, 39: 560, 4: 1080, 37: 457, 34: 2, 42: 18, 45: 246, 19: 40, 40: 1, 28: 794, 21: 648, 18: 1, 27: 987, 11: 761, 12: 274, 35: 743, 29: 1058, 7: 1, 25: 1, 48: 295, 8: 310})
community expectations mme from @l_modularity_function.py:{0: 0.00470940450079461, 1: 0.018467956168252198, 2: 0.003100121787398163, 3: 0.008876186369747569, 4: 0.010922904267384986, 5: 0.0007977377852030508, 6: 0.0216090169656288, 7: 0.007345999093640452, 8: 0.01560407105059214, 9: 0.07330313823642498, 10: 0.03723360621035225}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 380, 1: 368, 2: 80, 3: 60}
defaultdict(<class 'float'>, {29: 2258, 38: 2048, 45: 2514, 39: 2438, 17: 2635, 19: 2662, 44: 2623, 32: 2635, 26: 2147, 12: 2098, 34: 2550, 43: 2279, 47: 2577, 21: 1470, 4: 2669, 22: 2468, 11: 2548, 6: 2529, 30: 116, 40: 586, 20: 157})
defaultdict(<class 'float'>, {30: 1976, 33: 2326, 46: 2498, 0: 2248, 28: 2473, 49: 2241, 23: 2597, 13: 2431, 2: 2400, 42: 2555, 35: 2469, 14: 2550, 8: 2126, 3: 2477, 1: 1418, 24: 54, 5: 2493, 37: 2479, 16: 2133, 40: 905, 21: 374, 25: 28})
defaultdict(<class 'float'>, {25: 2140, 48: 2462, 10: 2193, 36: 1737, 26: 376, 15: 1976, 7: 2116, 24: 1393})
defaultdict(<class 'float'>, {41: 2317, 9: 2316, 31: 1287, 27: 2278, 20: 1271, 18: 2328, 1: 898, 36: 378})
community expectations mme from @l_modularity_function.py:{0: 0.16915886805970862, 1: 0.1596318753432511, 2: 0.007993839889005346, 3: 0.005139448340807697}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{1: 260, 3: 424, 4: 34, 2: 50, 0: 10, 5: 124}
defaultdict(<class 'float'>, {23: 2362, 30: 2362})
defaultdict(<class 'float'>, {17: 1123, 0: 507, 38: 1751, 20: 396, 44: 1261, 45: 1580, 21: 1776, 6: 1547, 43: 1637, 22: 1317, 46: 1589, 19: 424, 47: 1503, 24: 1527, 16: 1634, 36: 1655, 37: 435, 42: 957, 40: 1458, 15: 1355, 35: 1646, 5: 681, 1: 250})
defaultdict(<class 'float'>, {0: 1778, 28: 897, 5: 208, 25: 2738, 18: 2535, 17: 356, 43: 1, 22: 1})
defaultdict(<class 'float'>, {39: 2767, 8: 2623, 11: 2799, 2: 2555, 5: 387, 31: 2743, 27: 2534, 4: 2442, 13: 2654, 37: 1133, 34: 2556, 49: 2615, 7: 2781, 48: 2446, 14: 2626, 41: 874, 19: 1172, 26: 2422, 9: 2527, 12: 2623, 3: 2353, 42: 748, 32: 2676, 1: 590, 10: 2596, 16: 882, 17: 330, 38: 1})
defaultdict(<class 'float'>, {41: 849, 33: 2613, 29: 2038, 28: 1388})
defaultdict(<class 'float'>, {35: 825, 20: 1123, 6: 778, 19: 743, 40: 612, 24: 828, 44: 840, 22: 596, 42: 1, 43: 857, 46: 1047, 1: 917, 47: 970, 21: 880, 36: 393, 15: 158, 45: 280, 37: 8})
community expectations mme from @l_modularity_function.py:{0: 0.00011401190981298189, 1: 0.10883594887190655, 2: 0.004221837710894864, 3: 0.21934115321098177, 4: 0.0017896379896608363, 5: 0.032854541128876265}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 236, 3: 338, 2: 246, 1: 54, 4: 10}
defaultdict(<class 'float'>, {17: 2407, 35: 2536, 40: 2614, 27: 2546, 15: 2679, 20: 1555, 24: 2649, 36: 2729, 37: 1875, 46: 2714, 6: 2439, 43: 2635, 26: 1664, 29: 2615, 14: 158, 11: 1, 16: 1})
defaultdict(<class 'float'>, {25: 2750, 31: 443, 1: 2488, 10: 2623, 19: 2331, 14: 1})
defaultdict(<class 'float'>, {45: 2707, 49: 2716, 8: 2583, 13: 2705, 31: 329, 33: 39, 11: 743, 7: 2572, 28: 2391, 3: 2265, 0: 2676, 39: 2737, 16: 1875, 20: 1, 48: 666, 38: 632, 37: 222, 41: 1, 24: 64})
defaultdict(<class 'float'>, {22: 2716, 4: 2506, 47: 1538, 5: 2822, 30: 1890, 2: 2597, 42: 2626, 23: 2659, 12: 2441, 21: 2267, 34: 2281, 48: 865, 18: 2515, 32: 2773, 41: 2255, 11: 1265, 38: 1022, 31: 226, 14: 1474, 44: 2199, 26: 467, 16: 1, 20: 363})
defaultdict(<class 'float'>, {9: 1883, 33: 1883})
community expectations mme from @l_modularity_function.py:{0: 0.07059634176184865, 1: 0.003718177858322946, 2: 0.0732819889029541, 3: 0.130879247565371, 4: 0.0001278945218956682}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{4: 200, 0: 212, 1: 104, 2: 172, 5: 70, 3: 100}
defaultdict(<class 'float'>, {40: 2580, 0: 213, 32: 2356, 10: 2000, 13: 877, 41: 897, 35: 1981, 24: 2259, 23: 1973, 43: 2159, 31: 1618, 16: 1420, 4: 1473, 21: 845, 30: 2413, 37: 308, 2: 248, 48: 1, 18: 1, 46: 1})
defaultdict(<class 'float'>, {5: 2641, 44: 2262, 29: 1911, 26: 2557, 1: 2111, 20: 2317, 13: 708, 2: 558, 45: 1, 42: 2, 21: 1, 46: 1})
defaultdict(<class 'float'>, {47: 1656, 18: 2323, 45: 1227, 48: 132, 10: 136, 41: 152, 34: 2308, 12: 2391, 15: 110, 2: 678, 4: 394, 17: 2479, 3: 1752, 25: 130, 7: 2497, 42: 1052, 13: 1, 32: 1, 6: 1, 27: 31, 37: 129, 31: 1, 1: 1})
defaultdict(<class 'float'>, {37: 803, 6: 436, 46: 1, 22: 422, 39: 769, 28: 892, 36: 683, 0: 280, 38: 452, 45: 1, 47: 757, 27: 470, 48: 1, 8: 636, 11: 487, 25: 760, 33: 792, 23: 104, 15: 1, 16: 2, 24: 1})
defaultdict(<class 'float'>, {15: 1742, 22: 1488, 25: 1555, 48: 1397, 46: 1722, 11: 1355, 36: 739, 8: 1729, 6: 1725, 32: 1, 42: 10, 38: 1369, 45: 389, 28: 1442, 27: 1722, 21: 494, 0: 278, 33: 1446, 39: 1602, 13: 37, 16: 1, 31: 1, 23: 1, 1: 1, 4: 1})
defaultdict(<class 'float'>, {14: 2387, 41: 568, 9: 2304, 49: 2172, 19: 2045, 42: 1, 36: 24, 0: 482, 37: 1, 15: 1, 3: 4, 27: 1})
community expectations mme from @l_modularity_function.py:{0: 0.062311527068420164, 1: 0.01386674361637493, 2: 0.040368462834090776, 3: 0.021872844587928823, 4: 0.06290864258960223, 5: 0.006664189790629943}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{1: 270, 4: 118, 3: 98, 0: 132, 2: 64, 5: 122}
defaultdict(<class 'float'>, {12: 67, 24: 885, 45: 411, 9: 246, 11: 1, 13: 776, 2: 1780, 10: 37, 15: 1692, 0: 105, 18: 780, 31: 749, 39: 72, 47: 181, 29: 709, 27: 157, 43: 1190, 5: 1051, 30: 64, 36: 94, 21: 1, 42: 364, 35: 1, 8: 1, 34: 1})
defaultdict(<class 'float'>, {20: 2422, 7: 2554, 28: 2208, 22: 1796, 41: 623, 8: 1728, 32: 2466, 26: 436, 43: 107, 4: 2354, 3: 1678, 33: 2409, 9: 844, 49: 1834, 40: 2497, 14: 2351, 0: 119, 10: 586, 44: 2469, 35: 387, 27: 4, 46: 767, 48: 1081, 30: 1, 31: 84, 13: 30, 45: 22, 34: 128, 12: 1, 29: 1})
defaultdict(<class 'float'>, {23: 1480, 26: 657, 39: 15, 37: 1561, 38: 1048, 21: 1371, 36: 505, 27: 662, 6: 830, 10: 1})
defaultdict(<class 'float'>, {1: 2111, 16: 2097, 42: 218, 17: 2271, 15: 517, 11: 292, 47: 1688, 34: 308, 25: 2369, 29: 157, 46: 573, 2: 237, 23: 5, 12: 1, 27: 1})
defaultdict(<class 'float'>, {6: 615, 38: 541, 11: 387, 19: 500, 24: 419, 34: 716, 41: 341, 0: 697, 21: 409, 15: 119, 39: 828, 30: 438, 9: 625, 18: 949, 2: 1, 31: 367, 45: 384, 3: 105, 14: 1, 43: 1, 42: 47, 37: 70, 12: 1, 36: 196, 23: 160, 5: 572, 13: 365})
defaultdict(<class 'float'>, {30: 1044, 12: 559, 42: 678, 24: 585, 6: 299, 19: 1012, 39: 840, 31: 764, 0: 1087, 41: 806, 45: 1192, 13: 523, 36: 358, 11: 699, 29: 704, 48: 256, 38: 60, 10: 527, 22: 1, 34: 1, 49: 92, 43: 482})
community expectations mme from @l_modularity_function.py:{0: 0.03718758056694764, 1: 0.10250924103654789, 2: 0.007030546469291549, 3: 0.019616827074224193, 4: 0.03932206935736822, 5: 0.04557534655369613}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{2: 148, 3: 222, 1: 128, 0: 84, 4: 100, 5: 218}
defaultdict(<class 'float'>, {25: 1365, 7: 2484, 41: 2525, 38: 282, 48: 1096, 42: 1029, 32: 2510, 4: 515, 2: 139})
defaultdict(<class 'float'>, {38: 1005, 19: 1919, 24: 2731, 3: 2514, 44: 396, 45: 2744, 12: 683, 11: 2515, 42: 534, 39: 794, 47: 805, 30: 1023, 16: 370})
defaultdict(<class 'float'>, {26: 571, 30: 683, 22: 667, 18: 535, 29: 1057, 48: 1053, 33: 844, 31: 961, 8: 817, 0: 974, 39: 902, 1: 357, 28: 875, 4: 558, 15: 546, 35: 116, 49: 1034, 9: 706, 12: 1, 47: 340, 21: 179})
defaultdict(<class 'float'>, {35: 1517, 17: 2391, 46: 2471, 2: 1480, 16: 1792, 0: 709, 5: 2441, 34: 2650, 43: 2432, 6: 2552, 40: 764, 14: 2544, 13: 2647, 12: 440, 44: 189, 26: 1178})
defaultdict(<class 'float'>, {23: 2353, 10: 2543, 20: 2565, 27: 2289, 30: 98, 36: 2278, 40: 293, 49: 432, 37: 2487, 21: 154, 25: 627, 22: 407, 19: 239, 0: 1, 28: 57})
defaultdict(<class 'float'>, {9: 1634, 28: 1498, 22: 747, 29: 1603, 44: 998, 1: 1436, 49: 692, 18: 1573, 40: 876, 30: 255, 35: 536, 21: 1149, 43: 10, 47: 236, 4: 887, 8: 1286, 15: 1427, 33: 1424, 31: 1422, 2: 207, 39: 1, 0: 39})
community expectations mme from @l_modularity_function.py:{0: 0.009733013808913818, 1: 0.02641213149405826, 2: 0.04882507783469495, 3: 0.06798467116704995, 4: 0.016850721112947532, 5: 0.07586236398149303}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 298, 3: 270, 4: 94, 1: 16, 2: 220, 5: 42}
defaultdict(<class 'float'>, {19: 2578, 8: 1789, 48: 2364, 9: 2444, 13: 2522, 42: 2810, 22: 2797, 32: 1650, 38: 1693, 7: 228, 36: 1584, 2: 738, 26: 1003, 14: 658, 37: 2173, 17: 1557, 44: 1550, 43: 1588, 4: 2809, 45: 1185, 30: 1, 20: 371, 40: 1, 3: 1})
defaultdict(<class 'float'>, {5: 2322, 31: 2322, 2: 118, 36: 238})
defaultdict(<class 'float'>, {35: 1648, 29: 1716, 46: 1733, 24: 1532, 26: 607, 14: 1556, 34: 1798, 11: 453, 30: 1240, 40: 1716, 10: 1560, 28: 1508, 16: 1624, 32: 504, 12: 1446, 7: 1157, 0: 1973, 47: 668, 27: 1617, 1: 1631, 45: 1})
defaultdict(<class 'float'>, {23: 2691, 25: 2900, 35: 249, 21: 2677, 33: 2612, 49: 2855, 39: 2651, 20: 1887, 43: 745, 15: 2633, 28: 385, 41: 2388, 2: 881, 16: 1, 18: 2854, 44: 829, 3: 1693, 6: 337, 47: 1234, 17: 786, 7: 1, 40: 1})
defaultdict(<class 'float'>, {29: 803, 11: 694, 45: 763, 12: 697, 34: 480, 8: 377, 27: 820, 10: 1029, 30: 532, 16: 469, 28: 402, 40: 43, 38: 1, 24: 887, 1: 979, 3: 1, 0: 223, 47: 62, 46: 328, 32: 1})
defaultdict(<class 'float'>, {37: 261, 38: 462, 11: 604, 36: 10, 26: 423, 9: 196, 13: 1, 7: 70, 30: 373, 8: 146, 17: 139, 41: 371})
community expectations mme from @l_modularity_function.py:{0: 0.11983018538086462, 1: 0.0005636222426871748, 2: 0.06985884306280078, 3: 0.08357984754079678, 4: 0.019871738865223882, 5: 0.00566372695386489}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{3: 140, 5: 194, 4: 182, 0: 138, 1: 134, 2: 106}
defaultdict(<class 'float'>, {21: 1334, 35: 1541, 20: 885, 46: 499, 27: 1273, 37: 1286, 42: 1313, 44: 1645, 23: 273, 45: 689, 30: 280, 3: 1485, 47: 609, 13: 242, 36: 1, 17: 219, 32: 330, 25: 1})
defaultdict(<class 'float'>, {5: 2254, 15: 2653, 17: 1509, 4: 2319, 48: 2768, 26: 2753, 9: 2177, 46: 1090, 28: 262, 2: 267, 43: 13})
defaultdict(<class 'float'>, {44: 980, 25: 699, 23: 633, 31: 994, 33: 446, 28: 1158, 27: 858, 32: 244, 0: 1, 13: 506, 20: 355, 37: 1359, 35: 282, 3: 385, 47: 413, 21: 1, 30: 657, 42: 774})
defaultdict(<class 'float'>, {24: 2776, 7: 222, 47: 755, 38: 2799, 28: 391, 6: 1306, 41: 2753, 0: 899, 33: 884, 8: 846, 29: 1880, 32: 1000, 20: 368, 18: 716, 45: 2, 30: 1, 35: 1})
defaultdict(<class 'float'>, {12: 2484, 30: 511, 2: 1345, 33: 730, 36: 1592, 39: 2692, 8: 426, 0: 365, 19: 2437, 25: 680, 21: 90, 13: 1549, 34: 2647, 11: 2495, 31: 168, 3: 42, 23: 132, 40: 489, 32: 1})
defaultdict(<class 'float'>, {10: 2596, 7: 2237, 14: 2732, 31: 705, 45: 1097, 16: 2421, 22: 2444, 1: 2550, 21: 589, 33: 1, 18: 1085, 23: 535, 40: 1406, 8: 203, 49: 2700, 36: 326, 25: 1, 6: 498, 29: 348, 17: 15, 43: 1067})
community expectations mme from @l_modularity_function.py:{0: 0.03199676746165798, 1: 0.022351621117235317, 2: 0.028171098578363276, 3: 0.030872993244201986, 4: 0.04494963218358856, 5: 0.05189225829690168}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{5: 416, 4: 166, 1: 70, 2: 86, 0: 76, 3: 66}
defaultdict(<class 'float'>, {24: 919, 17: 68, 39: 877, 7: 219, 40: 864, 0: 1416, 14: 418, 5: 1, 38: 185, 26: 277, 21: 1010, 22: 90, 15: 465, 28: 665, 20: 1, 19: 1, 43: 1, 23: 1, 44: 36})
defaultdict(<class 'float'>, {14: 1599, 28: 1577, 24: 936, 2: 470, 30: 1079, 0: 278, 38: 1481, 21: 886, 43: 333, 39: 186, 7: 56, 1: 201, 26: 1})
defaultdict(<class 'float'>, {4: 2549, 8: 262, 40: 1162, 9: 2299, 27: 2507, 43: 1193, 23: 1688, 44: 1, 2: 1029, 21: 115, 14: 1, 24: 1, 32: 1, 7: 1})
defaultdict(<class 'float'>, {10: 443, 2: 491, 15: 540, 11: 494, 49: 80, 35: 188, 8: 530, 47: 472, 6: 1, 19: 36, 44: 229, 1: 1, 3: 433, 17: 621, 18: 8, 20: 280, 45: 1, 31: 1, 5: 155, 25: 1, 36: 1})
defaultdict(<class 'float'>, {7: 1096, 30: 1578, 13: 2680, 35: 1979, 38: 255, 33: 2451, 48: 350, 29: 1967, 6: 1776, 46: 1398, 41: 2116, 12: 39, 25: 1, 34: 2109, 21: 1, 24: 50, 42: 2722, 37: 1, 23: 196, 22: 226, 27: 60, 26: 48, 1: 1, 36: 1})
defaultdict(<class 'float'>, {49: 2252, 31: 2300, 10: 1636, 19: 1206, 11: 2052, 12: 1932, 5: 2014, 25: 2352, 1: 854, 44: 1392, 17: 915, 46: 1203, 3: 1967, 48: 1495, 47: 2103, 16: 2363, 45: 1875, 37: 1928, 8: 1488, 36: 2024, 15: 954, 29: 542, 35: 82, 22: 1561, 26: 797, 32: 2330, 20: 1618, 18: 1927, 39: 422})
community expectations mme from @l_modularity_function.py:{0: 0.011351913259251346, 1: 0.013097480735671787, 2: 0.012279841129666867, 3: 0.012844324201654284, 4: 0.04067829737912939, 5: 0.21528925027816415}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{7: 32, 3: 162, 2: 162, 0: 66, 8: 84, 1: 128, 5: 16, 4: 140, 6: 128}
defaultdict(<class 'float'>, {0: 1058, 42: 508, 5: 911, 2: 2456, 37: 97, 47: 246, 46: 575, 49: 2598, 27: 160, 33: 1297, 9: 86, 43: 162, 1: 79})
defaultdict(<class 'float'>, {21: 240, 35: 836, 18: 486, 26: 626, 15: 831, 24: 1, 34: 802, 42: 594, 19: 407, 48: 476, 23: 520, 16: 565, 44: 383, 43: 78, 38: 546, 22: 448, 46: 527, 13: 662, 25: 450, 1: 1, 20: 283, 10: 1, 37: 205, 12: 83, 45: 1})
defaultdict(<class 'float'>, {30: 1095, 7: 1521, 37: 238, 17: 1607, 41: 1548, 6: 1429, 9: 1128, 45: 1038, 14: 431, 21: 432, 3: 1602, 16: 1158, 15: 828, 18: 11, 31: 574, 8: 621, 46: 74, 27: 327, 19: 727, 32: 119})
defaultdict(<class 'float'>, {14: 403, 48: 101, 20: 805, 5: 535, 23: 529, 36: 1080, 13: 696, 4: 1135, 32: 1175, 33: 491, 43: 1, 10: 877, 35: 572, 22: 1157, 18: 983, 12: 1026, 21: 668, 27: 585, 29: 1567, 26: 841, 42: 1, 37: 1, 1: 583, 34: 415, 46: 113, 31: 138, 47: 643, 24: 570})
defaultdict(<class 'float'>, {38: 69, 43: 189, 37: 799, 41: 1061, 30: 899, 13: 508, 7: 976, 32: 881, 8: 794, 18: 1, 31: 844, 45: 1036, 17: 1011, 9: 538, 3: 331, 14: 809, 16: 204, 6: 942, 35: 1, 21: 569, 15: 50, 27: 1})
defaultdict(<class 'float'>, {12: 1, 36: 1670, 43: 64, 19: 105, 46: 1, 3: 1, 44: 27, 8: 1, 32: 1})
defaultdict(<class 'float'>, {19: 545, 35: 379, 13: 311, 25: 420, 18: 789, 44: 1024, 24: 981, 26: 422, 29: 552, 20: 507, 4: 965, 27: 2, 15: 221, 12: 898, 22: 243, 23: 757, 38: 276, 10: 482, 47: 289, 33: 365, 34: 237, 48: 135, 43: 566, 46: 79, 8: 1, 2: 1})
defaultdict(<class 'float'>, {10: 1, 35: 117, 43: 132, 41: 1, 8: 109, 47: 1, 25: 136, 23: 245, 37: 206, 16: 77, 38: 265, 6: 1, 45: 1, 42: 1, 17: 73})
defaultdict(<class 'float'>, {40: 2033, 39: 2242, 44: 432, 38: 622, 28: 2114, 3: 88, 34: 52, 14: 15, 11: 2325, 25: 615, 32: 1, 16: 1, 46: 1})
community expectations mme from @l_modularity_function.py:{0: 0.008545165911414557, 1: 0.03443367389149831, 2: 0.05565107735940728, 3: 0.049998658699670885, 4: 0.041246392801324853, 5: 0.0007551444973135082, 6: 0.03666642678749192, 7: 0.00256122397912973, 8: 0.009892180318577548}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{1: 408, 2: 26, 0: 350, 3: 28, 4: 44}
defaultdict(<class 'float'>, {19: 2442, 39: 2553, 26: 2385, 0: 2089, 35: 2524, 10: 1990, 16: 2138, 4: 2126, 23: 2144, 30: 2434, 5: 2288, 27: 2496, 9: 2246, 25: 2252, 40: 2139, 7: 2485, 3: 2482, 36: 2435, 42: 2448, 47: 2382})
defaultdict(<class 'float'>, {49: 1888, 12: 2427, 31: 2144, 24: 2406, 46: 2062, 15: 2231, 6: 2479, 11: 2253, 34: 2214, 48: 2184, 43: 2496, 1: 2438, 28: 2469, 14: 2191, 44: 2486, 32: 2442, 29: 2438, 45: 2397, 20: 2258, 37: 2180})
defaultdict(<class 'float'>, {13: 2313, 17: 2304, 18: 2418})
defaultdict(<class 'float'>, {21: 2459, 8: 2202, 22: 2180})
defaultdict(<class 'float'>, {41: 2415, 38: 2070, 33: 2359, 2: 2388})
community expectations mme from @l_modularity_function.py:{0: 0.15092384392190364, 1: 0.2031061332250509, 2: 0.0008359406203392773, 3: 0.0009457601284275256, 4: 0.002369930873880074}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 486, 2: 210, 3: 202, 1: 66}
defaultdict(<class 'float'>, {32: 2670, 35: 2497, 9: 2916, 6: 2762, 46: 2760, 40: 2855, 20: 2761, 22: 2747, 8: 2876, 12: 2876, 31: 2814, 14: 2822, 29: 2617, 28: 2786, 10: 2736, 7: 2440, 23: 2508, 16: 2265, 15: 2913, 17: 2535, 49: 2769, 39: 2711, 1: 2912, 41: 2849})
defaultdict(<class 'float'>, {48: 2396, 37: 2549, 38: 2807, 34: 2408, 3: 2591})
defaultdict(<class 'float'>, {5: 2647, 2: 2735, 47: 2717, 4: 2265, 19: 2828, 33: 2794, 27: 2470, 21: 2747, 42: 2951, 11: 2684, 0: 2914})
defaultdict(<class 'float'>, {30: 2895, 43: 2936, 45: 2287, 18: 2574, 36: 2692, 44: 2756, 26: 2824, 25: 2936, 13: 2187, 24: 2895})
community expectations mme from @l_modularity_function.py:{0: 0.23369526986243985, 1: 0.003805207956838163, 2: 0.04423202605453433, 3: 0.04031833294955587}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{2: 232, 0: 224, 1: 82, 3: 246, 4: 128}
defaultdict(<class 'float'>, {48: 2703, 14: 1836, 46: 1993, 20: 2478, 9: 2378, 42: 2864, 38: 2847, 8: 2797, 12: 1, 33: 2932, 2: 2756, 25: 2164, 6: 2793, 28: 1, 31: 1, 49: 1, 1: 1})
defaultdict(<class 'float'>, {7: 2810, 23: 2716, 0: 1972, 32: 2716, 18: 2775, 26: 2847, 49: 1, 28: 1})
defaultdict(<class 'float'>, {21: 2583, 36: 2672, 35: 2846, 31: 2491, 22: 2571, 29: 2744, 27: 2767, 43: 2726, 40: 2781, 11: 2418, 10: 2527, 24: 2365, 46: 1, 48: 28})
defaultdict(<class 'float'>, {15: 2497, 30: 2850, 45: 2906, 41: 2867, 39: 2810, 16: 2750, 5: 2813, 17: 2756, 34: 2486, 25: 1, 49: 2070, 37: 2286, 12: 2361, 1: 1, 14: 227, 10: 1, 28: 1})
defaultdict(<class 'float'>, {28: 2104, 31: 1, 3: 2651, 13: 1509, 19: 2449, 4: 2606, 47: 2639, 44: 2658, 11: 1, 1: 1949, 46: 1})
community expectations mme from @l_modularity_function.py:{0: 0.05515227911707755, 1: 0.007458683378242475, 2: 0.06021475074130478, 3: 0.0632027629348964, 4: 0.016624792684950353}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{0: 132, 6: 90, 3: 56, 2: 298, 1: 120, 5: 48, 4: 168}
defaultdict(<class 'float'>, {4: 563, 8: 863, 38: 757, 45: 761, 39: 181, 15: 637, 17: 608, 40: 2, 48: 99, 27: 1157, 12: 1101, 33: 1, 43: 849, 28: 966, 49: 536, 25: 1, 7: 419, 37: 93, 31: 1157, 22: 231, 23: 961, 44: 910, 21: 674, 35: 23, 42: 1})
defaultdict(<class 'float'>, {7: 365, 34: 1440, 41: 572, 3: 565, 10: 938, 32: 662, 23: 1738, 28: 1, 43: 618, 38: 63, 49: 319, 17: 149, 47: 77, 21: 281, 31: 1, 40: 537, 48: 197, 44: 892, 12: 293, 13: 183, 35: 11, 15: 171, 36: 13, 37: 1, 45: 276, 8: 188, 25: 98, 39: 2, 4: 2})
defaultdict(<class 'float'>, {9: 2564, 20: 2726, 29: 1845, 6: 2831, 14: 2761, 33: 2599, 30: 2512, 0: 2559, 11: 2678, 2: 2271, 46: 2747, 36: 2234, 19: 2575, 26: 2054, 40: 1, 42: 1, 35: 1, 39: 1, 4: 5, 22: 1, 7: 1, 17: 2, 15: 1})
defaultdict(<class 'float'>, {12: 1, 5: 2574, 24: 2574, 18: 2564, 16: 2649, 1: 20, 48: 298, 40: 2, 25: 1, 32: 1, 38: 1})
defaultdict(<class 'float'>, {21: 387, 28: 574, 37: 707, 15: 118, 25: 242, 49: 293, 17: 437, 47: 613, 32: 835, 38: 353, 1: 1, 35: 555, 41: 1, 22: 1, 13: 419, 48: 478, 8: 417, 40: 624, 43: 806, 45: 874, 7: 871, 27: 719, 44: 43, 10: 265, 39: 886, 2: 1, 34: 245, 31: 719, 23: 3, 0: 43, 3: 82, 26: 1, 4: 1})
defaultdict(<class 'float'>, {1: 795, 22: 497, 49: 600, 39: 16, 38: 724, 48: 415, 35: 67, 3: 336, 21: 1, 13: 398, 15: 273, 25: 416, 17: 1, 12: 1, 32: 1, 8: 1})
defaultdict(<class 'float'>, {25: 688, 48: 195, 1: 1303, 10: 1194, 13: 895, 47: 887, 49: 17, 37: 306, 7: 297, 17: 152, 41: 997, 34: 337, 21: 1, 32: 234, 39: 117, 19: 1, 22: 327, 35: 219, 15: 74, 38: 302, 29: 1, 40: 1})
community expectations mme from @l_modularity_function.py:{0: 0.034353314302240354, 1: 0.03204159753840825, 2: 0.09144154918304613, 3: 0.0037187706536525324, 4: 0.04487185820095059, 5: 0.008212391304888012, 6: 0.01999003003855461}

/Users/acw721/Desktop/research/linkstream/Baseline.py:23: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(link_stream_file, header=None, index_col=False,names=["source","destination","timestamp"], skiprows=1)

community nb interaction:{2: 140, 0: 248, 1: 314, 3: 50, 4: 130}
defaultdict(<class 'float'>, {9: 1672, 12: 1232, 36: 1732, 4: 1478, 42: 1495, 15: 1031, 46: 613, 1: 1188, 40: 1400, 23: 1397, 11: 1050, 49: 989, 19: 1690, 17: 704, 7: 1400, 44: 2, 20: 18, 45: 87, 35: 1519, 18: 1215, 47: 1607, 14: 1451, 13: 1343, 43: 1, 28: 1})
defaultdict(<class 'float'>, {26: 2670, 10: 2829, 22: 1868, 30: 2601, 6: 2759, 25: 2565, 8: 1065, 33: 2663, 17: 200, 38: 2749, 5: 2289, 3: 2143, 0: 2648, 31: 1329, 32: 2369, 34: 2816, 20: 2168, 16: 1664, 41: 1573, 46: 325, 1: 1, 13: 46, 11: 2, 44: 512, 45: 3, 35: 1, 42: 1, 12: 1, 49: 1, 2: 2})
defaultdict(<class 'float'>, {39: 2443, 37: 2452, 2: 1652, 48: 2590, 19: 12, 24: 2462, 21: 2471, 27: 2622, 44: 1, 16: 1, 12: 205, 42: 263, 46: 324, 8: 1, 29: 2282, 22: 48, 45: 206, 1: 6, 23: 107, 17: 200, 28: 244})
defaultdict(<class 'float'>, {35: 377, 40: 714, 13: 759, 23: 726, 44: 401, 41: 1, 28: 704, 43: 1080, 17: 532, 12: 30, 2: 1, 15: 1, 45: 1, 47: 1, 46: 1})
defaultdict(<class 'float'>, {4: 976, 13: 141, 36: 395, 28: 312, 19: 740, 15: 1211, 43: 510, 42: 192, 11: 904, 9: 726, 32: 7, 12: 47, 49: 1178, 1: 710, 40: 44, 17: 1, 18: 1033, 45: 504, 7: 1134, 14: 724, 20: 1, 44: 669, 16: 270, 23: 179, 35: 188, 47: 1})
community expectations mme from @l_modularity_function.py:{0: 0.0954424198148874, 1: 0.11205039257287787, 2: 0.02921199696175773, 3: 0.007399787626627031, 4: 0.04285508060880974}